### PR TITLE
Create Contributing.md

### LINKED ISSUE #9: DOCS: Improve Contributing.md file
### Description

Presently, the instructions for contributing to this project are vague and short.

- Improve the contributing.md file

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by sshikhar09**
Created a basic, short and accurate Contributing.md containing the link to the issues page and instructions as to how to make the first pull request.
 Closes #9 
Kindly merge this under hacktoberfest.

- [ ] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by AkashR04 — CHANGES_REQUESTED** [review]
Write the guidelines you have to follow while you are fixing an issue to the Contribution file so that the creator can easily understand the changes.

**Comment by AkashR04** [comment]
If you can give me the code style you work with I can create the Contribution.md file

**Comment by sshikhar09** [comment]
Kindly read this and merge under hacktoberfest.
Ref. #9 
@slim-codes

**Review by slim-codes — APPROVED** [review]
This file is too short and non-comprehensive

**Comment by slim-codes** [comment]
> Kindly read this and merge under hacktoberfest. Ref. #9 @slim-codes

@sshikhar09 
This contributing.md file is not **concise** as required by issue #9. Plus, you are making this PR from your **main** branch which isn't advisable to do as you yourself specified in the file you have just created. I typically dismiss this kind of PR's. However, I shall merge it under hacktoberfest because you are probably new to this, but next time make a quality PR to whatever project you are contributing to. Thank you

**Comment by slim-codes** [comment]
@AkashR04 
Make a PR for this if you can make a proper Contribution file
Thank you

**Comment by sshikhar09** [comment]
@slim-codes thank you for the advice. I am new to this and i don't know the work culture. Therefore, I apologize for my mistakes. I hope to learn from this and do better in this field.

**Pull request merged**
